apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: airplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      hostNetwork: true
      containers:
      - name: discord-bot
        image: airplay-discord-bot:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            configMapKeyRef:
              name: discord-config
              key: DISCORD_TOKEN
        - name: VOICE_CHANNEL_ID
          valueFrom:
            configMapKeyRef:
              name: discord-config
              key: VOICE_CHANNEL_ID
        volumeMounts:
        - name: pipe-data
          mountPath: /tmp
      volumes:
      - name: pipe-data
        emptyDir: {}
