apiVersion: apps/v1
kind: Deployment
metadata:
  name: shairport-sync
  namespace: airplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shairport-sync
  template:
    metadata:
      labels:
        app: shairport-sync
    spec:
      hostNetwork: true
      containers:
      - name: shairport-sync
        image: mikebrady/shairport-sync:4.1-classic
        securityContext:
          capabilities:
            add:
            - SYS_NICE
        volumeMounts:
        - name: config
          mountPath: /etc/shairport-sync.conf
          subPath: shairport-sync.conf
        - name: pipe-data
          mountPath: /tmp
      volumes:
      - name: config
        configMap:
          name: shairport-config
      - name: pipe-data
        emptyDir: {}
